### ISSUE TITLE
it maybe unavailable

### ISSUE THREAD

**Issue by modaye** [abstra-app/abstra-lib#2]
```shell
(.venv) > abstra serve


ABSTRA EDITOR RUNNING: http://localhost:3000/_editor


A new version of Abstra Editor is available. Latest version is 1.8.20, but you have 0.0.0.
Please run 'pip install abstra --upgrade' to update.


Error writing to abstra.json
 * Serving Flask app 'abstra_server.apps'
 * Debug mode: off
[2023-08-21 10:43:17,534] ERROR in app: Exception on /_editor/api/forms/ [GET]
Traceback (most recent call last):
  File "F:\AnyTask\Learn\.venv\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AnyTask\Learn\.venv\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AnyTask\Learn\.venv\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "F:\AnyTask\Learn\.venv\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AnyTask\Learn\.venv\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AnyTask\Learn\.venv\Lib\site-packages\abstra_server\usage.py", line 32, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "F:\AnyTask\Learn\.venv\Lib\site-packages\abstra_server\apps\editor.py", line 55, in get_forms
    return [f.editor_dto for f in api.get_forms()]
                                  ^^^^^^^^^^^^^^^
  File "F:\AnyTask\Learn\.venv\Lib\site-packages\abstra_server\api\__init__.py", line 106, in get_forms
    abstra_json = self.__get_abstra_json()
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AnyTask\Learn\.venv\Lib\site-packages\abstra_server\api\__init__.py", line 58, in __get_abstra_json
    self.abstra_json_path.read_text(encoding="utf-8")
  File "C:\Program Files\Python311\Lib\pathlib.py", line 1058, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\pathlib.py", line 1044, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'abstra.json'
```

**Comment by brunovcosta** [comment]
Hey @modaye, thank you for your feedback!

I just notice this was a windows specific bug and we solved it in [v1.8.23](https://github.com/abstra-app/abstra-lib/releases/tag/v1.8.23).

Let me know if there is anything else we can help!

**Comment by modaye** [comment]
It has generated a new error and cannot replicate the temporary file to absra.json

**Comment by modaye** [comment]
@brunovcosta I am pulling code to fix it, but accessing github is very slow, so I have to wait for a while

**Comment by brunovcosta** [comment]
I don't recommend you installing from the repo. Have you tried `pip install abstra`?

The `master` branch is not guaranteed to be stable

**Comment by modaye** [comment]
@brunovcosta Yes, exactly from `pip install abstra`
